export const SIGNIN_REQ = 'SIGNIN_REQ';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const ENROLL_REQ = 'ENROLL_REQ';
export const ENROLL_SUCCESS = 'ENROLL_SUCCESS';
export const ENROLL_FAILURE = 'ENROLL_FAILURE';

export const UPDATE_USER_REQ = 'UPDATE_USER_REQ';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
