export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const GET_VIDEO_URL = 'GET_VIDEO_URL';
export const GET_VIDEO_TITLE = 'GET_VIDEO_TITLE';
export const GET_VIDEO_ID = 'GET_VIDEO_ID';

export const GET_COURSENAME_REQ = 'GET_COURSENAME_REQ';
export const GET_COURSENAME_SUCCESS = 'GET_COURSENAME_SUCCESS';
export const GET_COURSENAME_FAILURE = 'GET_COURSENAME_FAILURE';
