export const GET_ALL_COURSES_REQ = 'GET_ALL_COURSES_REQ';
export const GET_ALL_COURSES_SUCCESS = 'ADD_CAMPAIGN_SUCCESS';
export const GET_ALL_COURSES_FAILURE = 'GET_ALL_COURSES_FAILURE';

export const ADD_COURSE_REQ = 'ADD_COURSE_REQ';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FALIURE';
