export const GET_ALL_COURSES_REQ = 'GET_ALL_COURSES_REQ';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAILURE = 'GET_ALL_COURSES_FAILURE';

export const ADD_COURSE_REQ = 'ADD_COURSE_REQ';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FALIURE';

export const GET_ALL_VIDEOS_PC_REQ = 'GET_ALL_VIDEOS_PC_REQ';
export const GET_ALL_VIDEOS_PC_SUCCESS = 'GET_ALL_VIDEOS_PC_SUCCESS';
export const GET_ALL_VIDEOS_PC_FAILURE = 'GET_ALL_VIDEOS_PC_FALIURE';
