export default [
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    level: 'Intermediate',
    course: true,
    img: '',
  },
  {
    title: 'The Good, the Bad and the Ugly',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    level: 'Intermediate',
    course: false,

    img: '',
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    level: 'Intermediate',
    course: true,

    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },

  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: true,
    level: 'Intermediate',
    img: '',
  },
  {
    title: 'Pulp Fiction',
    year: 1994,
    university: 'The Hong Kong University of Sci and Tech.',
    rating: '4.7 (9546)',
    students: 300,
    course: false,
    level: 'Intermediate',
    img: '',
  },
];
